# fly.toml app configuration file generated for oxycare-project-skahvq on 2025-07-02T20:26:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oxycare-project-skahvq'
primary_region = 'cdg'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
