"""Make patient_id nullable in dispositifs_medicaux

Revision ID: 6caad8d2d45b
Revises: 
Create Date: 2025-05-28 15:22:48.612460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6caad8d2d45b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositifs_medicaux', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('prescripteurs', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('prenom',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescripteurs', schema=None) as batch_op:
        batch_op.alter_column('prenom',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('dispositifs_medicaux', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
